spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cryptocurrency?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: sanna0319
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show-sql: true
    hibernate:
      ddl-auto: none
logging:
  file:
    name: logs/app.log
  level:
    com:
      whitebear: ERROR
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{115} - %msg%n"
    file: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{115} - %msg%n"
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-handlers-package: com.whitebear.model
#  mapper-locations: classpath:mybatis/*.xml
#  type-aliases-package: com.whitebear.model
#
#jwt-config:
#  subtracted-days: 15
#  jwtSecret: bitcoinServerSecretKey
#  jwtExpInMinute: 1440